### ISSUE TITLE
Issue with config/policies.js

### ISSUE THREAD

**Issue by rishab-yumist** [cludden/sails-must#6]
Hello,

If I have my controllers in api/controllers/v1/, when I try to write policies, it doesn't apply on them.

Here's my config/policies.js code

![screen shot 2016-01-19 at 6 48 39 pm](https://cloud.githubusercontent.com/assets/13828707/12419617/4d3c4f6c-bedd-11e5-95ad-acffaaf92928.png)
![screen shot 2016-01-19 at 6 48 43 pm](https://cloud.githubusercontent.com/assets/13828707/12419618/4d3c4f62-bedd-11e5-9393-b6d694d97881.png)

Could you help me with the same?

Thanks in advance. @cludden

**Comment by cludden** [comment]
hey @rishab-yumist 
if your project structure looks like this:
- /api
  - /controllers
    - /v1
      - EventController.js
  - /policies
  - /policyFactories
    - member.js
- /config
  - policies.js

then to apply a policy or policy factory to the `EventController`, you need to prefix the relative path of the controller to the controller name, like so

``` javascript
// in /config/policies.js
module.exports.policies = {
    // ..
    'v1/EventController': {
        '*': must().be.a.member()
    }
    // ..
}
```

**Comment by rishab-yumist** [comment]
Hello @cludden ,

I tried using this. It throws an error.

![screen shot 2016-01-19 at 8 11 33 pm](https://cloud.githubusercontent.com/assets/13828707/12421578/dc70ac5e-bee8-11e5-8277-2e6ad2b5e074.png)

**Comment by cludden** [comment]
can you give some additional info? node version? sails version? also, you're policyFactory file if that's cool?

**Comment by rishab-yumist** [comment]
Sure @cludden , here are the details : 
Sails version 0.11.3
Node version 4.2.3

![screen shot 2016-01-19 at 8 20 49 pm](https://cloud.githubusercontent.com/assets/13828707/12421868/28d553c8-beea-11e5-89d0-0a2844ae5a8b.png)

api/policies/member.js
![screen shot 2016-01-19 at 8 21 08 pm](https://cloud.githubusercontent.com/assets/13828707/12421881/37101de2-beea-11e5-9381-6f3d7bc1d716.png)

config/policies.js
![Uploading Screen Shot 2016-01-19 at 8.22.35 pm.png…]()

**Comment by cludden** [comment]
Oh I think I see the issue, I don't believe you can put policyFactories in the `/policies` folder, as this folder is reserved by sails for traditional policies. Try moving it to `/api/policyFactories/member.js` and change your require statement to reflect the move:

``` javascript
// in /config/policies
var must = require('sails-must')({
    helpers: ['to', 'of', 'at', 'a'],
    response: function(err, errors, req, res, next) {
        // ...
    }
})
```

**Comment by rishab-yumist** [comment]
Hard luck, still getting the same error.

![screen shot 2016-01-19 at 8 28 30 pm](https://cloud.githubusercontent.com/assets/13828707/12422110/449ce6b0-beeb-11e5-95c7-b16dc54d4072.png)

Folder structure 

![screen shot 2016-01-19 at 8 29 28 pm](https://cloud.githubusercontent.com/assets/13828707/12422128/5e2f9dca-beeb-11e5-9150-8855a4d6cc3c.png)

**Comment by cludden** [comment]
hmm, do you `sails-hook-must` installed and have you disabled the default policy hook?

**Comment by rishab-yumist** [comment]
Hey @cludden , I found what the issue was, my .sailsrc file was missing. I added it and it works like a wonder. Thanks for your help :)

**Comment by cludden** [comment]
Awesome!
